# Generated by Django 5.2 on 2025-05-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_authenticator_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='google_authenticator_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
